# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Wollok-ts-cli CI

on:
  push:
    tags:
      - 'v*'
    

jobs:
  release:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-22.04, windows-2022]

    permissions:
      contents: write

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
    - name: Install dependencies
      run: npm install
    - name: Build cli
      run: npm run build
    - name: Build and publish artifacts
      run: npm run release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}